apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-villa-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuber-villa-project
  template:
    metadata:
      labels:
        app: kuber-villa-project
    spec:
      containers:
        - name: kuber-villa-project
          image: pobbathikeerthana/kuber-villa-project
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Served by $(hostname)" >> /usr/local/apache2/htdocs/index.html && \
              httpd-foreground