apiVersion: v1
kind: Service
metadata:
  name: kuber-villa-project-service
spec:
  type: LoadBalancer
  selector:
    app: kuber-villa-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80